### ISSUE TITLE
Problem installing with Ansible

### ISSUE THREAD

**Issue by kvdnberg** [allegro/tipboard#43]
Hi,

I'm hoping you can help me with the folllowing: For a collaborative tipboard-based project I'm trying to set up a Vagrant box (debian based) with Ansible. 

```
- name: Install pip libraries
  pip:
    name: "{{ item }}"
  with_items:
    - tipboard
```
When running `vagrant provision` I get the following error:

```
    "item": "tipboard",
    "msg": "stdout: Collecting tipboard\n  Using cached tipboard-1.4.1.tar.gz\nCollecting mock==1.0.1 (from tipboard)\n  Using cached mock-1.0.1.zip\nCollecting PyYAML==3.10 (from tipboard)\n  Using cached PyYAML-3.10.tar.gz\nCollecting redis==2.7.5 (from tipboard)\n  Using cached redis-2.7.5.tar.gz\nCollecting requests==1.2.3 (from tipboard)\n  Using cached requests-1.2.3.tar.gz\n    Complete output from command python setup.py egg_info:\n    Traceback (most recent call last):\n      File \"<string>\", line 1, in <module>\n      File \"/tmp/pip-build-kBU_Al/requests/setup.py\", line 6, in <module>\n        import requests\n      File \"requests/__init__.py\", line 53, in <module>\n        from requests.packages.urllib3.contrib import pyopenssl\n      File \"requests/packages/urllib3/contrib/pyopenssl.py\", line 42, in <module>\n        ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,\n    AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'\n    \n    ----------------------------------------\n\n:stderr: Command \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-build-kBU_Al/requests/\n"
}
```

It seems there's an issue with requests 1.2.3 perhaps in combination with other packages in the box?

**Comment by ghost** [comment]
AFAIK debian disabled SSLv3 so this may cause error.
Try follow:
http://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue

**Comment by kvdnberg** [comment]
@xliiv I did see that page actually and I can install tipboard fine inside the Vagrant box in virtualenv but I would like it to be done by ansible. I managed to fix the ansible by setting it up like this:

```
- name: Install tipboard
  pip:
    chdir: "/vagrant"
    name: "{{ item }}"
    virtualenv: "/vagrant/my-virtualenv-name"
  with_items:
    - tipboard
```

Thanks for the input!
