### ISSUE TITLE
Cols before Rows

### ISSUE THREAD

**Issue by akiskin** [allegro/tipboard#49]
Hello all!

Is it possible to put COLs before ROWs in config yaml file?
Secondly, how to make somthing like colspan / rowspan (as in html)?

Sorry for using issues on github, did not find any other means of contact.

**Comment by ghost** [comment]
I'm not sure what you mean by "put cols before rows",  you mean in yml file? What are you trying to do?
About spans..
Here's the doc https://tipboard.readthedocs.io/en/latest/configuration.html#customising-tile-layout
including link https://github.com/allegro/tipboard/blob/develop/tipboard/static/css/layout.css#L68 describing CSS behind that.
If you give more concrate example then the answer will be more concrate ;)

**Comment by akiskin** [comment]
Wow, thanks for fastest possible reaction.

Looking at https://tipboard.readthedocs.io/en/latest/configuration.html#sample-layout I want to switch cols with rows: to have in result col_1_of_2 -> rows(1-2-3), col_2_of_2 -> rows(1-2)

**Comment by ghost** [comment]
Unfortunately it's not possible right now because the order is fixed here:
https://github.com/allegro/tipboard/blob/develop/tipboard/templates/layout.html#L22

**Comment by akiskin** [comment]
Ok, got it.

Can you give an example of colspan/rowspan then?
Like in http://allegro.tech/tipboard/img/example-dashboards/Dashboard2.png "Work time"?

**Comment by ghost** [comment]
Try this:
```
layout:
    row_1_of_2:
        col_1_of_4:
        col_1_of_4:
        col_1_of_4:
        col_1_of_4:
    row_1_of_2:
        col_1_of_4:
        col_1_of_4:
        col_2_of_4:
```
